import 'package:eye_scrim/globalWidgets/dataTilePreView.dart';
import 'package:eye_scrim/globalWidgets/dateTile.dart';

final List<DataTiles> dataList = [
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "인하대",
    sexIndex: 0,
    stateIndex: 0,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 3,
    univ: "연세대",
    sexIndex: 0,
    stateIndex: 1,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "광운대",
    sexIndex: 0,
    stateIndex: 2,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "인천대",
    sexIndex: 1,
    stateIndex: 1,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 4,
    univ: "숭실대",
    sexIndex: 1,
    stateIndex: 1,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "인하공전",
    sexIndex: 0,
    stateIndex: 0,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "인하대",
    sexIndex: 0,
    stateIndex: 2,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "인하대",
    sexIndex: 0,
    stateIndex: 0,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 3,
    univ: "연세대",
    sexIndex: 0,
    stateIndex: 1,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "광운대",
    sexIndex: 0,
    stateIndex: 2,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "인천대",
    sexIndex: 1,
    stateIndex: 1,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 4,
    univ: "숭실대",
    sexIndex: 1,
    stateIndex: 1,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "인하공전",
    sexIndex: 0,
    stateIndex: 0,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "인하대",
    sexIndex: 0,
    stateIndex: 2,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "인하대",
    sexIndex: 0,
    stateIndex: 0,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 3,
    univ: "연세대",
    sexIndex: 0,
    stateIndex: 1,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "광운대",
    sexIndex: 0,
    stateIndex: 2,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "인천대",
    sexIndex: 1,
    stateIndex: 1,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 4,
    univ: "숭실대",
    sexIndex: 1,
    stateIndex: 1,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "인하공전",
    sexIndex: 0,
    stateIndex: 0,
  ),
  DataTiles(
    name: 'aaa',
    peopleNum: 2,
    univ: "인하대",
    sexIndex: 0,
    stateIndex: 2,
  ),
];

final List<DataTilePreView> dataListPreview = [
  DataTilePreView(
    name: 'aaa',
    peopleNum: 2,
    univ: "인하대",
    sexIndex: 0,
    stateIndex: 0,
  ),
  DataTilePreView(
    name: 'aaa',
    peopleNum: 3,
    univ: "연세대",
    sexIndex: 0,
    stateIndex: 1,
  ),
  DataTilePreView(
    name: 'aaa',
    peopleNum: 2,
    univ: "광운대",
    sexIndex: 0,
    stateIndex: 2,
  ),
  DataTilePreView(
    name: 'aaa',
    peopleNum: 2,
    univ: "인천대",
    sexIndex: 1,
    stateIndex: 1,
  ),
  DataTilePreView(
    name: 'aaa',
    peopleNum: 4,
    univ: "숭실대",
    sexIndex: 1,
    stateIndex: 1,
  ),
  DataTilePreView(
    name: 'aaa',
    peopleNum: 2,
    univ: "인하공전",
    sexIndex: 0,
    stateIndex: 0,
  ),
  DataTilePreView(
    name: 'aaa',
    peopleNum: 2,
    univ: "인하대",
    sexIndex: 0,
    stateIndex: 2,
  ),
];
